# Updates

## Network construction

### Nodes

1. Generate a GxS gene absence presence matrix from the pipeline's output (CD-Hit).  It has:  
- clusters as rows  
- samples as columns

| | sample1 | sample2 | sample3 | ... | sampleN |
|---|---------|---------|---------|-----|---------|
| cluster1 | 1 | 0 | 1 | ... | 0 |
| cluster2 | 0 | 1 | 0 | ... | 1 |
| ... | ... | ... | ... | ... | ... |
| clusterN | 1 | 1 | 0 | ... | 1 |

Clusters can be associated with an a representative gene that has a patric ID - each cluster will have a product name.   
The pipleine provides a pangenome annotation file that associates each cluster to being either core, accessory or unique.

A way to associate each cluster with resistance is by computing the odds ration of resistance (also found in a other works)

|  | resistant | susceptible |
|---|-----------|-------------|
| gene present | a | b |
| gene absent | c | d |


$log(odds) = log(\frac{a*d}{b*c})$  
_can be colored by a divergent continuous mapping when visualized_

Cluster (nodes) attributes:  
- patric_ID  
- product_name  
- log_odds  
- pan_annotation

### Edges

For edges to be defined as interactions between genes (epistatic interactions), we need to define a metric that quantifies the interaction between two genes.  
Genes in the (_transposed_) GxS presence matrix are features, hence interaction between features define the edges. 

**How to model gene-gene interaction:**  


Following the approach in Kavvas et al. (2018) that worked on gene-gene interactions while studying the resistance in _M. tuberculosis_:  

1. Started by training a 200 randomized SVM ensemble on the _alleles_ presence matrix. They took the following assumptions:  
    - weight of feature = contribution in resistance
    - positive weight = resistance & negative weight = susceptibility
    - magnitude & sign of a gene **depends** on magnitude and signs of other genes in the same hyperplane
    - randomization (they employed bootstrapping & SGD - with l1 penalty) is implemented to ensure variability of a. weights, b. signs and c. set of genes in each hyperplane for each model in the ensemble

They only took the models with AUC>0.8 now they have the following: 

|  | gene1 | gene2 | gene3 | ... | geneN |
|---|-------|-------|-------|-----|-------|
| model1 | w1 | w2 | w3 | ... | wN |
| model2 | w1 | w2 | w3 | ... | wN |
| ... | ... | ... | ... | ... | ... |
| model200 | w1 | w2 | w3 | ... | wN |

Then computed the correlation between gene weights, ending up with a GxG matrix.


Implemented 200 SVM models without bootstrapping (don't want to take a subset of the data) & without val/test split because hte goal is not prediction (accuracy wont matter, I want to detect interaction), and without SGD as well (no variability).

2. 